<stmt> ::= <expr>
         | <fun-def>
         | <if-bloc>

<expr> ::= <declare-assign>

<dotted> ::= <"var-name" expr>
           | <"base" dotted> "." <"var-name" expr>

<assign> ::= <"assignTo" assignable> "=" <"value" expr>

<type> ::= <"type-name" string>

<declare-assign> ::= <"var-name" string> ":" <"type" type>
                   | <"var-name" string> ":" <"type" type> "=" <"value" expr>

<param> ::= <"var-name" string> ":" <"var-type" type>
          | <"var-name" string> ":" <"var-type" type> ","

<fun-def> ::= "def" <"func-name"> "(" ["params" param] ")" "{" <"body" stmt> "}"

<if-bloc> ::= "if" "(" <"cond" expr> ")" "{" <"body" stmt> "}"
<while-bloc> ::= "while" "(" <"cond" expr> ")" "{" <"body" stmt> "}"

<add> ::= <"op1" expr> "+" <"op2" expr>
<sub> ::= <"op1" expr> "-" <"op2" expr>
<mul> ::= <"op1" expr> "*" <"op2" expr>
<div> ::= <"op1" expr> "/" <"op2" expr>

<inc> ::= <"op1" expr> "++"
<dec> ::= <"op1" expr> "--"
